# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acquire_fcs_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_acquire_fcs_data(object):
    def setupUi(self, acquire_fcs_data):
        acquire_fcs_data.setObjectName("acquire_fcs_data")
        acquire_fcs_data.resize(565, 242)
        self.label = QtWidgets.QLabel(acquire_fcs_data)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(acquire_fcs_data)
        self.progressBar.setGeometry(QtCore.QRect(90, 90, 411, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_current_file = QtWidgets.QLabel(acquire_fcs_data)
        self.label_current_file.setGeometry(QtCore.QRect(80, 20, 471, 16))
        self.label_current_file.setObjectName("label_current_file")
        self.button_start = QtWidgets.QPushButton(acquire_fcs_data)
        self.button_start.setGeometry(QtCore.QRect(150, 160, 72, 23))
        self.button_start.setObjectName("button_start")
        self.button_exit = QtWidgets.QPushButton(acquire_fcs_data)
        self.button_exit.setGeometry(QtCore.QRect(320, 160, 72, 23))
        self.button_exit.setObjectName("button_exit")

        self.retranslateUi(acquire_fcs_data)
        QtCore.QMetaObject.connectSlotsByName(acquire_fcs_data)

    def retranslateUi(self, acquire_fcs_data):
        _translate = QtCore.QCoreApplication.translate
        acquire_fcs_data.setWindowTitle(_translate("acquire_fcs_data", "Acquire FCS files"))
        self.label.setText(_translate("acquire_fcs_data", "Processing:"))
        self.label_current_file.setText(_translate("acquire_fcs_data", "(file name)"))
        self.button_start.setText(_translate("acquire_fcs_data", "Start"))
        self.button_exit.setText(_translate("acquire_fcs_data", "Exit"))
