# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'folder_monitor_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_folder_to_monitor_setting(object):
    def setupUi(self, folder_to_monitor_setting):
        folder_to_monitor_setting.setObjectName("folder_to_monitor_setting")
        folder_to_monitor_setting.resize(400, 158)
        self.groupBox = QtWidgets.QGroupBox(folder_to_monitor_setting)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 371, 111))
        self.groupBox.setObjectName("groupBox")
        self.txt_folder_select = QtWidgets.QLineEdit(self.groupBox)
        self.txt_folder_select.setGeometry(QtCore.QRect(10, 30, 351, 20))
        self.txt_folder_select.setObjectName("txt_folder_select")
        self.btn_select_folder = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_folder.setGeometry(QtCore.QRect(40, 70, 75, 23))
        self.btn_select_folder.setObjectName("btn_select_folder")
        self.btn_confirm_folder = QtWidgets.QPushButton(self.groupBox)
        self.btn_confirm_folder.setGeometry(QtCore.QRect(230, 70, 75, 23))
        self.btn_confirm_folder.setObjectName("btn_confirm_folder")

        self.retranslateUi(folder_to_monitor_setting)
        QtCore.QMetaObject.connectSlotsByName(folder_to_monitor_setting)

    def retranslateUi(self, folder_to_monitor_setting):
        _translate = QtCore.QCoreApplication.translate
        folder_to_monitor_setting.setWindowTitle(_translate("folder_to_monitor_setting", "Folder To Monitor"))
        self.groupBox.setTitle(_translate("folder_to_monitor_setting", "Folder"))
        self.btn_select_folder.setText(_translate("folder_to_monitor_setting", "Select"))
        self.btn_confirm_folder.setText(_translate("folder_to_monitor_setting", "confirm"))
